---
title: "TidyTuesdays from 2021-2 class"
output: github_document
bibliography: packages.bib
nocite: "@*"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")


knitr::write_bib(renv::dependencies()$Package, file = "packages.bib") # Line to write the all packages references in a file called packages.bib
```

The following code chunk have the essential libraries for the subsequent code.
```{r libraries, warning=FALSE, message=FALSE}
library(tidyverse, warn.conflicts = FALSE)
library(tidytuesdayR)

tuesdata <- tidytuesdayR::tt_load(2021, week = 44)

<<<<<<< HEAD
rankings <- tuesdata$ultra_rankings
=======
rankings <-  tuesdata$ultra_rankings
>>>>>>> amaliamunera-main
```
 
 Estudiantes:

## Alexandra

```{r Alexandra}
# Make the histogram
rankings %>%
  filter( age<90 ) %>%
  ggplot( aes(x=age)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8)
```


## Amalia

```{r Amalia}
library(report)
library(dplyr)
library(ggsci)

rankings <- tuesdata$ultra_rankings

modified_rankings <- rankings %>%
  mutate(time_in_minutes = time_in_seconds / 60)

ggplot(modified_rankings , aes(x = time_in_minutes , fill = gender)) + geom_density(data = modified_rankings , alpha = 0.6) + theme_minimal() + labs(x = "Time in minutes", y = "Gender") + theme( legend.position = "left" , legend.title = element_blank()) + ggtitle("Proggress of gender vs time") + scale_fill_tron()
 
```

## Andrés

```{r Andres}

library(report)

rankings <-  tuesdata$ultra_rankings

rankings_modified <- rankings %>%
  mutate(time_in_hours = time_in_seconds / 3600)

  

p <- ggplot(rankings_modified, aes(x = time_in_hours, y = age))  
p + geom_point(aes(colour = factor(gender),shape =gender)) +
  labs(x='time (hr)', y = 'age' ) +
    theme(legend.position = 'down' ) +
  scale_fill_viridis_b()
 
 
```

## Manuela

```{r Manuela}
library(report)

rankings <-  tuesdata$ultra_rankings

# rankings %>%
# summary() para visualizar datos
# glimpse() otra manera de visualizar los datos


# report(rankings)

 rankings_modified <- rankings %>% 
   mutate(time_in_hours = time_in_seconds / 3600) %>% 
   drop_na()
  
ggplot(rankings_modified, aes(x = time_in_hours, y = gender, fill=gender)) +
  geom_violin()
  

```

## Maria José

```{r MariaJose}
library(ggplot2)
library(dplyr)

rankings <- tuesdata$ultra_ranking

rankings_modified <-mutate(rankings, time_in_hours=time_in_seconds/3600)

ggplot(rankings_modified, aes (x=age, y=time_in_hours,fill=gender))+
  geom_violin()


```

## Pablo

```{r Pablo,warning=FALSE,message=FALSE}
library(tidytuesdayR)

# rankings <- tuesdata$ultra_rankings

# tuesdata$ultra_rankings

  

# Libraries..

# library(hrbrthemes)
# library(dplyr)
# library(tidyr)
# library(viridis)
# library(ggplot2)

# Make the histogram....

#rankings %>%
  #mutate(time_in_hours = time_in_seconds / 3600)


 p2 <- ggplot(data=rankings, aes(x=time_in_seconds, group=age, fill=age)) +
    geom_density(adjust=1.5, alpha=0.4) +
    theme_minimal()
 p2
```

## Susana

```{r Susana}


library(ggplot2)
library(wesanderson)
theme_set(theme_classic()) 
# head(rankings)
data_frame <- na.omit(rankings)
# head(data_frame)
p <- ggplot(data_frame, aes(x = age, fill = gender)) + 
geom_density(alpha = 0.4) + scale_fill_manual(values = wes_palette("GrandBudapest2")) +
labs(title = "Tidy Tuesday ", x = "Age", y = "Density") + theme(plot.title = element_text(size = 14, face = "bold")) + theme(plot.title = element_text(hjust = 0.5))
p

```

# References